# Pandas-Dataframe and Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data clearning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array like object, while a DataFrame is a two dimensional, size-mutable, and potentially heterogenous tabular data structure with labeled axes (rows and columns)

In [2]:
import pandas as pd

In [6]:
# Series: It's a one dimensional array like object that can hold any data type
data = [1,2,3,4,5,6,7,8,9,10]
series = pd.Series(data,name='Number')
print('Series \n',series)

Series
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Number, dtype: int64

In [7]:
# Create a series from dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)
series_dict

a    1
b    2
c    3
dtype: int64

a    1
b    2
c    3
dtype: int64

In [8]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [11]:
# DataFrame
# Create a Dataframe from dictionary of list
data = {
    'Name':['Huzefa', 'John','Jane'],
    'Age' : [25, 30,45],
    'City': ['Pune', 'New York','California']
}

df = pd.DataFrame(data)
print("Data type of DataFrame: ", type(df))
df

Data type of DataFrame:  <class 'pandas.core.frame.DataFrame'>

     Name  Age        City
0  Huzefa   25        Pune
1    John   30    New York
2    Jane   45  California

In [13]:
import numpy as np
np.array(df)

array([['Huzefa', 25, 'Pune'],
       ['John', 30, 'New York'],
       ['Jane', 45, 'California']], dtype=object)

In [22]:
# Create a DataFrame from a list of dictionaries
data = [ 
    {'Name': 'Huzefa' , 'Age': 31 , 'City': 'Pune'},
    {'Name': 'John' , 'Age': 30, 'City':'New York'},
    {'Name': 'Jane', 'Age': 38, 'City':'California'}
]

df = pd.DataFrame(data)
df

     Name  Age        City
0  Huzefa   31        Pune
1    John   30    New York
2    Jane   38  California

In [23]:
# Accessing column or series in a datafram
df['Name']

0    Huzefa
1      John
2      Jane
Name: Name, dtype: object

In [30]:
df.loc[0:]['Name']

0    Huzefa
1      John
2      Jane
Name: Name, dtype: object

In [ ]:
# Accessing a specified element
df.at[1,'Age']

np.int64(30)

In [38]:
df.at[1,'Name']

'John'

In [40]:
df.iat[1,2]

'New York'

In [43]:
# Data manipulation with DataFrame
df['Salary'] = [50000,60000,70000] # Adding a new column
df

     Name  Age        City  Salary
0  Huzefa   31        Pune   50000
1    John   30    New York   60000
2    Jane   38  California   70000

In [45]:
# Remove a column
df.drop('Salary',inplace=True,axis=1)
df

     Name  Age        City
0  Huzefa   31        Pune
1    John   30    New York
2    Jane   38  California

In [46]:
# Update the age column
df['Age'] = df['Age']+1
df

     Name  Age        City
0  Huzefa   32        Pune
1    John   31    New York
2    Jane   39  California

In [66]:
df.iloc[[0,1],[0,1]]

     Name  Age
0  Huzefa   32
1    John   31

In [67]:
# Reading csv files
df = pd.read_csv("Online Sales Data.csv")

In [68]:
# Print the first 10 rows
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [69]:
# Print the last 10 rows
df.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [70]:
# Accessing data from Dataframe
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
df.describe() #Statistical analysis of dataframe

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000