# Data Manipulation and Analysis with Pandas
Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [38]:
import pandas as pd
df = pd.read_csv('data.csv') # Read the csv file

In [39]:
# Print the first 5 rows
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [40]:
df.describe() # Statistical information about the data

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [41]:
df.dtypes # To check the data type of the columns

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [42]:
# Handling missing values
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [43]:
df.isnull().sum() #Checking the values where there are missing values

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [44]:
# Filling missing values
df_fill = df.fillna(0)
df_fill.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [45]:
# Indentifying a mean value for a specific column
df['Sales'].mean()

np.float64(557.1304347826087)

In [46]:
# Filling missing values with the menan of the column
df['Sales'].fillna(df['Sales'].mean(),inplace=True)
df.head()

C:\Users\battih\AppData\Local\Temp\ipykernel_22696\3647290168.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sales'].fillna(df['Sales'].mean(),inplace=True)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [47]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [ ]:
# Rename columns
df.rename(columns={'Date':'Sales Date'},inplace=True)
df.head()

   Sales Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [52]:
# Chnage the data type of columns
df['Value'].fillna(df['Value'].mean(), inplace=True)
df['Value_new']  = df['Value'].astype(int)
df.head()

C:\Users\battih\AppData\Local\Temp\ipykernel_22696\4054415490.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Value'].fillna(df['Value'].mean(), inplace=True)

   Sales Date Category  Value   Product  Sales Region  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         28
1  2023-01-02        B   39.0  Product3  110.0  North         39
2  2023-01-03        C   32.0  Product2  398.0   East         32
3  2023-01-04        B    8.0  Product1  522.0   East          8
4  2023-01-05        B   26.0  Product3  869.0  North         26

In [53]:
df['New Value'] = df['Value'].apply(lambda x: x*2)
df.head()

   Sales Date Category  Value   Product  Sales Region  Value_new  New Value
0  2023-01-01        A   28.0  Product1  754.0   East         28       56.0
1  2023-01-02        B   39.0  Product3  110.0  North         39       78.0
2  2023-01-03        C   32.0  Product2  398.0   East         32       64.0
3  2023-01-04        B    8.0  Product1  522.0   East          8       16.0
4  2023-01-05        B   26.0  Product3  869.0  North         26       52.0

In [54]:
# Data Aggregating and Geouping
df.groupby('Product')['Value'].mean()

Product
Product1    46.905585
Product2    52.800000
Product3    54.986562
Name: Value, dtype: float64

In [ ]:
# Using groupby to evaluate mean value at product and region level
df.groupby(['Product','Region'])['Value'].mean()

Product   Region
Product1  East      41.714286
          North     20.248227
          South     50.000000
          West      74.436170
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     42.457447
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [ ]:
# Using groupby to evaluate cumulative value at product and region level
df.groupby(['Product','Region'])['Value'].sum()

Product   Region
Product1  East      292.000000
          North      60.744681
          South     100.000000
          West      297.744681
Product2  East       56.000000
          North     127.000000
          South     181.000000
          West      428.000000
Product3  East      202.000000
          North     254.744681
          South     215.000000
          West      373.000000
Name: Value, dtype: float64

In [60]:
# Using groupby to evaluate cumulative value at product and region level
df.groupby(['Product','Region'])['Value'].agg(['sum','mean','count'])

                        sum       mean  count
Product  Region
Product1 East    292.000000  41.714286      7
         North    60.744681  20.248227      3
         South   100.000000  50.000000      2
         West    297.744681  74.436170      4
Product2 East     56.000000  28.000000      2
         North   127.000000  63.500000      2
         South   181.000000  60.333333      3
         West    428.000000  53.500000      8
Product3 East    202.000000  50.500000      4
         North   254.744681  42.457447      6
         South   215.000000  71.666667      3
         West    373.000000  62.166667      6

In [62]:
# Merging and joining data frame
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [64]:
pd.merge(df1,df2,how='inner',on='Key')

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [65]:
pd.merge(df1,df2, on='Key',how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [66]:
pd.merge(df1,df2, on='Key',how='left')

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [67]:
pd.merge(df1,df2, on='Key',how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [70]:
pd.merge(df1,df2, how='cross')

  Key_x  Value1 Key_y  Value2
0     A       1     A       4
1     A       1     B       5
2     A       1     D       6
3     B       2     A       4
4     B       2     B       5
5     B       2     D       6
6     C       3     A       4
7     C       3     B       5
8     C       3     D       6